# Generated by Django 3.0.3 on 2020-02-12 10:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('joe_rogan', '0002_auto_20200210_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='joeroganpost',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joeroganpost',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='joeroganpost',
            name='_quotes',
            field=models.CharField(default='[]', max_length=8192),
        ),
    ]
